name: tasky_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # API Client
  dio: ^5.5.0+1
  retrofit: ^4.1.0

  # State Management
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  # Annotation
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0

  # Other
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generator
  build_runner: ^2.4.11
  retrofit_generator: ^8.1.1
  riverpod_generator: ^2.4.0

  # Data Class
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  # Lint
  flutter_lints: ^2.0.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
